#!/usr/bin/env python3
"""
The Deconstructed Standard Model Lagrangian — in Python
=======================================================

This program exemplifies the Standard Model equation as presented in
Symmetry Magazine's "The deconstructed Standard Model equation"
(Rashmi Shivni, 07/28/16), which walks through T.D. Gutierrez's
transcription of the full Lagrangian (derived from Veltman's
*Diagrammatica*) in five sections:

  Section 1: Gluons — the strong force, 8 self-interacting color charges
  Section 2: W, Z and photon — electroweak boson interactions
  Section 3: Matter — three generations of fermions, the weak force,
             Yukawa/Higgs couplings (with the famous flaw: massless neutrinos)
  Section 4: Higgs "ghosts" — Goldstone modes of the Higgs field
  Section 5: Faddeev–Popov ghosts — bookkeeping fields that cancel
             gauge redundancies

Rather than merely printing the equation, each section *derives* a
characteristic piece of physics symbolically with SymPy:

  * SU(3) structure constants are computed from the Gell-Mann matrices,
    and the gluon Lagrangian is expanded to expose the 3-gluon and
    4-gluon self-interaction vertices.
  * The W/Z/photon mass spectrum is derived by diagonalizing the
    electroweak mass matrix generated by the Higgs vacuum value
    (the photon comes out exactly massless).
  * Fermion masses are tied to Yukawa couplings (m = y v / sqrt(2)),
    and the CKM quark-mixing matrix is checked for unitarity.
  * The Higgs potential is expanded around its vacuum to show one
    massive Higgs boson and three massless Goldstone ("Higgs ghost")
    modes.
  * The Faddeev–Popov ghost term is constructed from the same SU(3)
    structure constants as Section 1.

Requires: sympy, numpy      Run: python3 standard_model_lagrangian.py
"""

import sympy as sp
import numpy as np
from sympy import I, Rational, sqrt, conjugate, simplify, expand

BAR = "=" * 72


def header(title: str) -> None:
    print(f"\n{BAR}\n{title}\n{BAR}")


# ----------------------------------------------------------------------
# The whole thing (compact form)
# ----------------------------------------------------------------------
def the_whole_thing() -> None:
    header("THE WHOLE THING — the Standard Model Lagrangian (compact form)")
    print("""
Gutierrez's page-long transcription is the fully expanded version of a
Lagrangian that fits on a coffee mug:

    L = -1/4 F_uv F^uv                (all gauge fields: gluons, W, Z, photon)
        + i psibar (D-slash) psi      (matter kinetic terms + gauge couplings)
        + psibar_i y_ij psi_j phi     (Yukawa couplings to the Higgs) + h.c.
        + |D_u phi|^2 - V(phi)        (Higgs kinetic term and potential)

Expanding every implicit sum (8 gluons, 3 weak bosons, 3 generations,
gauge-fixing terms, ghosts...) is what produces the giant equation in
the article. The five sections below unpack it.""")


# ----------------------------------------------------------------------
# Section 1: Gluons
# ----------------------------------------------------------------------
def gell_mann_matrices() -> list:
    """The eight generators of SU(3), lambda_1 ... lambda_8."""
    l1 = sp.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 0]])
    l2 = sp.Matrix([[0, -I, 0], [I, 0, 0], [0, 0, 0]])
    l3 = sp.Matrix([[1, 0, 0], [0, -1, 0], [0, 0, 0]])
    l4 = sp.Matrix([[0, 0, 1], [0, 0, 0], [1, 0, 0]])
    l5 = sp.Matrix([[0, 0, -I], [0, 0, 0], [I, 0, 0]])
    l6 = sp.Matrix([[0, 0, 0], [0, 0, 1], [0, 1, 0]])
    l7 = sp.Matrix([[0, 0, 0], [0, 0, -I], [0, I, 0]])
    l8 = sp.Matrix([[1, 0, 0], [0, 1, 0], [0, 0, -2]]) / sqrt(3)
    return [l1, l2, l3, l4, l5, l6, l7, l8]


def su3_structure_constants(lams: list) -> dict:
    """
    f^{abc} from [lambda_a, lambda_b] = 2i f^{abc} lambda_c,
    i.e. f^{abc} = Tr([lambda_a, lambda_b] lambda_c) / (4i).
    Returns the nonzero constants keyed by 1-based (a, b, c) with a<b<c.
    """
    f = {}
    for a in range(8):
        for b in range(a + 1, 8):
            comm = lams[a] * lams[b] - lams[b] * lams[a]
            for c in range(b + 1, 8):
                val = sp.simplify(sp.trace(comm * lams[c]) / (4 * I))
                if val != 0:
                    f[(a + 1, b + 1, c + 1)] = val
    return f


def section_1_gluons() -> None:
    header("SECTION 1 — Gluons: the strong force (three lines of the equation)")

    lams = gell_mann_matrices()
    f = su3_structure_constants(lams)

    print("\nGluons carry a color charge described by SU(3). Its eight")
    print("generators (Gell-Mann matrices) fix the structure constants")
    print("f^{abc} via  [lambda_a, lambda_b] = 2i f^{abc} lambda_c.")
    print("\nNonzero structure constants (computed, not looked up):")
    for (a, b, c), val in f.items():
        print(f"    f^{{{a}{b}{c}}} = {val}")

    # Verify the closure/commutator relation for every pair (a strong
    # internal consistency check of the algebra).
    def f_full(a, b, c):
        """Totally antisymmetric extension of the a<b<c table (1-based)."""
        perm = {(0, 1, 2): 1, (1, 2, 0): 1, (2, 0, 1): 1,
                (0, 2, 1): -1, (2, 1, 0): -1, (1, 0, 2): -1}
        key = tuple(sorted((a, b, c)))
        if key not in f:
            return sp.Integer(0)
        order = tuple(key.index(x) for x in (a, b, c))
        return perm.get(order, 0) * f[key]

    ok = True
    for a in range(1, 9):
        for b in range(1, 9):
            comm = lams[a - 1] * lams[b - 1] - lams[b - 1] * lams[a - 1]
            recon = sp.zeros(3)
            for c in range(1, 9):
                recon += 2 * I * f_full(a, b, c) * lams[c - 1]
            if sp.simplify(comm - recon) != sp.zeros(3):
                ok = False
    print(f"\nCheck  [lambda_a, lambda_b] = 2i f^abc lambda_c  for all 64 pairs: "
          f"{'PASSED' if ok else 'FAILED'}")

    # --- Expand the gluon Lagrangian to expose self-interactions -------
    print("\nThe gluon field strength is")
    print("    G^a_uv = d_u A^a_v - d_v A^a_u + g_s f^{abc} A^b_u A^c_v")
    print("and the three lines of Section 1 come from  L_1 = -1/4 G^a_uv G^{a,uv}.")

    gs = sp.Symbol("g_s", positive=True)
    dA, A, fs = sp.symbols("(dA) A f", commutative=True)  # schematic amplitudes

    # Schematic field strength: derivative piece + self-interaction piece.
    G = 2 * dA + gs * fs * A**2          # (d_u A_v - d_v A_u) ~ 2 dA
    L1 = expand(Rational(-1, 4) * G**2)
    poly = sp.Poly(L1, gs)

    labels = {
        0: "free gluon propagation (kinetic term)",
        1: "THREE-gluon vertex  ~ g_s  f^{abc} (dA^a) A^b A^c",
        2: "FOUR-gluon vertex   ~ g_s^2 f^{abc} f^{ade} A^b A^c A^d A^e",
    }
    print("\nExpanding -1/4 G^2 and grouping by powers of the strong coupling g_s:")
    for power in range(3):
        coeff = poly.coeff_monomial(gs**power)
        print(f"    O(g_s^{power}): {sp.sstr(coeff * gs**power):<24}"
              f" <-- {labels[power]}")

    print("\nThe g_s and g_s^2 terms are why gluons interact among themselves —")
    print("photons have no analogue of f^{abc}, so light does not self-interact.")


# ----------------------------------------------------------------------
# Section 2: W and Z bosons (and the photon)
# ----------------------------------------------------------------------
def section_2_electroweak() -> None:
    header("SECTION 2 — W and Z bosons: electroweak interactions "
           "(almost half the equation)")

    g, gp, v = sp.symbols("g g' v", positive=True)
    W1, W2, W3, B = sp.symbols("W1 W2 W3 B", real=True)

    s1 = sp.Matrix([[0, 1], [1, 0]])
    s2 = sp.Matrix([[0, -I], [I, 0]])
    s3 = sp.Matrix([[1, 0], [0, -1]])

    # Higgs doublet frozen at its vacuum value.
    phi_vev = sp.Matrix([0, v / sqrt(2)])

    # Covariant derivative acting on the (constant) vacuum: only the
    # gauge-field piece survives.
    Dphi = -I * Rational(1, 2) * (
        g * (s1 * W1 + s2 * W2 + s3 * W3) + gp * B * sp.eye(2)
    ) * phi_vev

    mass_terms = sp.expand(simplify((Dphi.H * Dphi)[0]))
    print("\nFreeze the Higgs field at its vacuum value (0, v/sqrt(2)) and")
    print("evaluate the kinetic term |D_u phi|^2. What survives are boson")
    print("mass terms generated by the Higgs mechanism:\n")
    sp.pprint(mass_terms)

    # Charged sector: W± = (W1 ∓ i W2)/sqrt(2)  →  M_W = g v / 2
    W_mass_sq = sp.expand(mass_terms).coeff(W1**2)  # coefficient of W1^2 = M_W^2/2... 
    # mass term convention: (1/2) M^2 W1^2 for a real field
    M_W = sqrt(2 * W_mass_sq)
    print(f"\nCharged W mass:   M_W = {sp.sstr(simplify(M_W))}")

    # Neutral sector: mass matrix in the (W3, B) basis.
    Mmat = sp.Matrix([
        [sp.expand(mass_terms).coeff(W3**2) * 2,
         sp.expand(mass_terms).coeff(W3 * B)],
        [sp.expand(mass_terms).coeff(W3 * B),
         sp.expand(mass_terms).coeff(B**2) * 2],
    ])
    print("\nNeutral-sector mass matrix in the (W3, B) basis:")
    sp.pprint(Mmat)

    eigs = Mmat.eigenvals()
    print("\nIts eigenvalues (the squared masses of the physical particles):")
    for val, mult in eigs.items():
        val = simplify(val)
        name = "PHOTON  (exactly massless!)" if val == 0 else "Z BOSON"
        print(f"    M^2 = {sp.sstr(val):<20} <-- {name}")

    print("""
So the physical particles are mixtures of the original fields:
    Z      =  cos(theta_W) W3 - sin(theta_W) B      with tan(theta_W) = g'/g
    photon =  sin(theta_W) W3 + cos(theta_W) B
    W+-    =  (W1 -+ i W2)/sqrt(2)
and M_Z = M_W / cos(theta_W) > M_W, exactly as measured (91.19 vs 80.4 GeV).
The bulk of Section 2 in the full equation is the swarm of WWZ, WWA,
WWWW, WWZZ, ... self-interaction vertices among these bosons.""")


# ----------------------------------------------------------------------
# Section 3: Matter particles and the weak force
# ----------------------------------------------------------------------
def section_3_matter() -> None:
    header("SECTION 3 — Three generations of matter, the weak force, "
           "and Higgs couplings")

    y, v = sp.symbols("y v", positive=True)
    print("\nA Yukawa term  -y (psibar_L phi psi_R + h.c.)  turns into a mass")
    print("term when the Higgs settles at phi -> v/sqrt(2):")
    m = y * v / sqrt(2)
    print(f"\n    m_fermion = y v / sqrt(2) = {sp.sstr(m)}")

    v_num = 246.22  # GeV, Higgs vacuum expectation value
    fermions = {  # masses in GeV (PDG values)
        "electron": 0.000511, "muon": 0.10566, "tau": 1.77686,
        "up": 0.00216, "charm": 1.27, "top": 172.69,
        "down": 0.00467, "strange": 0.0934, "bottom": 4.18,
    }
    print(f"\nInverting for the Yukawa couplings (v = {v_num} GeV):")
    print(f"    {'fermion':<10}{'mass (GeV)':>14}{'Yukawa y':>14}")
    for name, mass in fermions.items():
        yy = mass * np.sqrt(2) / v_num
        print(f"    {name:<10}{mass:>14.6g}{yy:>14.3g}")
    print("    " + "-" * 38)
    print(f"    {'neutrinos':<10}{'0 (assumed)':>14}{'0':>14}   <-- the equation's")
    print("                                              known flaw: neutrino")
    print("                                              oscillations prove m > 0.")

    print("\nThe weak force also mixes the three quark generations through the")
    print("CKM matrix, which lets heavy quarks decay into lighter ones:")

    # Wolfenstein parametrization (PDG central values).
    lam, Aw, rho, eta = 0.2250, 0.826, 0.159, 0.348
    V = np.array([
        [1 - lam**2 / 2, lam, Aw * lam**3 * (rho - 1j * eta)],
        [-lam, 1 - lam**2 / 2, Aw * lam**2],
        [Aw * lam**3 * (1 - rho - 1j * eta), -Aw * lam**2, 1],
    ])
    rows, cols = ["u", "c", "t"], ["d", "s", "b"]
    print("\n    |V_CKM| (magnitudes):")
    print("          " + "".join(f"{c:>9}" for c in cols))
    for r, row in zip(rows, np.abs(V)):
        print(f"       {r}  " + "".join(f"{x:>9.4f}" for x in row))

    unitarity = np.max(np.abs(V.conj().T @ V - np.eye(3)))
    print(f"\n    Unitarity check  max|V†V - 1| = {unitarity:.1e}")
    print("    (~lambda^4 — exactly the accuracy of this truncated")
    print("     parametrization; the full CKM matrix is exactly unitary.)")
    print("    The tiny complex phase (eta) is the Standard Model's only")
    print("    source of CP violation — matter/antimatter asymmetry.")


# ----------------------------------------------------------------------
# Section 4: Higgs ghosts (Goldstone modes)
# ----------------------------------------------------------------------
def section_4_higgs_ghosts() -> None:
    header("SECTION 4 — Higgs ghosts: virtual artifacts of the Higgs field")

    lam_c, v = sp.symbols("lambda v", positive=True)
    H, phi0 = sp.symbols("H phi^0", real=True)
    phip = sp.Symbol("phi^+")  # complex charged Goldstone

    # Full Higgs doublet: physical Higgs H plus the "ghost" fields
    # phi+ and phi0 that appear all over Gutierrez's transcription.
    phi = sp.Matrix([phip, (v + H + I * phi0) / sqrt(2)])

    phi2 = sp.expand(simplify((phi.H * phi)[0]))
    mu2 = lam_c * v**2  # minimization condition of V = -mu^2|phi|^2 + lam|phi|^4
    V = sp.expand(-mu2 * phi2 + lam_c * phi2**2)

    print("\nWrite the Higgs doublet around its vacuum as")
    print("    phi = ( phi+ , (v + H + i phi0)/sqrt(2) )")
    print("and expand the potential V = -mu^2 |phi|^2 + lambda |phi|^4")
    print("(using the minimum condition mu^2 = lambda v^2).")
    print("\nQuadratic (mass) terms of the expansion:")

    # Pure mass terms: take the quadratic coefficient of each field with
    # every OTHER field switched off (otherwise quartic cross-terms leak in).
    quad = {
        "H^2      (physical Higgs boson)":
            V.coeff(H, 2).subs({phi0: 0, phip: 0}),
        "phi0^2   (neutral Higgs ghost)":
            V.coeff(phi0, 2).subs({H: 0, phip: 0}),
        "phi+phi- (charged Higgs ghosts)":
            V.coeff(phip * conjugate(phip)).subs({H: 0, phi0: 0}),
    }
    quad = {label: simplify(coeff) for label, coeff in quad.items()}
    for label, coeff in quad.items():
        print(f"    coefficient of {label:<34}: {sp.sstr(coeff)}")

    mH = simplify(sqrt(2 * quad["H^2      (physical Higgs boson)"]))
    print(f"\n    =>  m_H = {sp.sstr(mH)} = sqrt(2 lambda) v   "
          "(one massive Higgs boson)")
    print("    =>  phi0, phi+, phi- are MASSLESS Goldstone modes.")
    print("""
In the gauge used in the article's equation, these three modes appear as
independent 'Higgs ghost' fields with their own interaction terms —
Section 4 of the transcription. Physically they are not new particles:
they are the degrees of freedom the W+, W- and Z bosons 'eat' to become
massive (a massless vector has 2 polarizations; a massive one needs 3).""")


# ----------------------------------------------------------------------
# Section 5: Faddeev–Popov ghosts
# ----------------------------------------------------------------------
def section_5_faddeev_popov() -> None:
    header("SECTION 5 — Faddeev–Popov ghosts: cancelling gauge redundancies")

    print("""
Quantizing a gauge theory by summing over 'all field configurations'
overcounts, because many configurations are the same physics written in
different gauges. The fix (Faddeev & Popov, 1967) is to add fictitious
anticommuting scalar fields — ghosts cbar^a, c^a, one per gauge boson —
whose loop contributions exactly cancel the overcounting:

    L_ghost = cbar^a ( -d^2 delta^{ac} - g f^{abc} A^b_u d^u ) c^c

Note the SAME structure constants f^{abc} from Section 1 reappear: the
ghosts must know about the gauge group to cancel its redundancy. In the
article's equation these are the fields written as eta (and the X's for
the electroweak sector). Ghosts never appear as external, detectable
particles — they live only inside loops.

Ghost bookkeeping (one ghost/antighost pair per gauge boson):""")
    bosons = [("gluons (SU(3))", 8), ("weak bosons W1,W2,W3 (SU(2))", 3),
              ("hypercharge B (U(1))", 1)]
    total = 0
    for name, n in bosons:
        total += n
        print(f"    {name:<32} -> {n} ghost pair{'s' if n > 1 else ''}")
    print(f"    {'TOTAL':<32} -> {total} ghost pairs")
    print("""
(The U(1) ghost decouples in an abelian theory — its f^{abc} = 0 — which
is why plain electromagnetism never needed ghosts in the first place.)""")


# ----------------------------------------------------------------------
if __name__ == "__main__":
    print(BAR)
    print("THE DECONSTRUCTED STANDARD MODEL EQUATION")
    print("after Symmetry Magazine (2016) / T.D. Gutierrez / Veltman")
    print(BAR)

    the_whole_thing()
    section_1_gluons()
    section_2_electroweak()
    section_3_matter()
    section_4_higgs_ghosts()
    section_5_faddeev_popov()

    header("EPILOGUE")
    print("""
Every derived result above — the 8 self-interacting gluons, the massless
photon emerging next to a heavy Z, masses proportional to Yukawa
couplings, three eaten Goldstone modes, and 12 ghost pairs — is one
thread of the single page-long equation on the coffee mug.

(Gutierrez notes he introduced one sign error somewhere in his
transcription. Good luck finding it!)""")
